### ISSUE TITLE
How to build a library in c++?

### ISSUE THREAD

**Issue by rbonghi** [officinerobotiche/orblibcpp#3]
I compiled this library and I have the ".a" file. To release this library, I create a dir with ".a" library file and put ".h" in https://github.com/officinerobotiche/orblibcpp/tree/master/include, this is right?

@Myzhar 
cc @bobboteck

**Comment by Myzhar** [comment]
For a static linking this is right.

**Comment by Myzhar** [comment]
For a static linking this is right.
