### ISSUE TITLE
Packet to set/get the speed of the motors singularly

### ISSUE THREAD

**Issue by Myzhar** [officinerobotiche/orblibcpp#5]
At this stage with the library you can set/get the speed of the robot only according to unicycle cinematic model (v_forward + w_rotation).
It should be very useful to have two new packets to send the rotation speed to a single motor in rad/sec and to read the rotation speeds in the same in the same way, for a total of four new packets 

We can use these new packets to regulate PIDs and to move the robot cinematic model to high level electronics.

@rbonghi

**Comment by rbonghi** [comment]
I think to build a new message type of:

``` c
typedef struct motors {
   long left;
   long right;
}motors_t;
```

Second way

``` c
#define NUM_MOTORS 2
typedef long motors_t[NUM_MOTORS];
```

compliant with https://github.com/officinerobotiche/uNAV.X/issues/27

Which do you prefer?

**Comment by Myzhar** [comment]
I prefer the second

2015-01-16 9:51 GMT+01:00 Raffaello Bonghi notifications@github.com:

> I think to build a new message type of:
> 
> typedef struct motors {
>    long left;
>    long right;
> }motors_t;
> 
> Second way
> 
> #define NUM_MOTORS 2typedef long motors_t[NUM_MOTORS];
> 
> compliant with officinerobotiche/uNAV.X#27
> https://github.com/officinerobotiche/uNAV.X/issues/27
> 
> What do you prefer?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/officinerobotiche/orblibcpp/issues/5#issuecomment-70224604
> .

## 

_Walter "Myzhar" Lucetti_

email myzhar@robot-home.it
web: _www.robot-home.it http://www.robot-home.it/ - www.opencv.it
http://www.opencv.it/_
project:  http://myzharbot.robot-home.it

**Comment by rbonghi** [comment]
:+1:

**Comment by rbonghi** [comment]
Update type message in:

``` c
typedef struct motor_control{
    int16_t motor[NUM_MOTORS];
}motor_control_t;
#define LNG_MOTOR_CONTROL sizeof(motor_control_t)
```

**Comment by rbonghi** [comment]
Temporary change packet in:

``` c
/**
 * Message to control single motor
 * - dimension number motors
 */
#define MOTOR_TYPE_REQ 0
#define MOTOR_TYPE_SEND 1
typedef struct motor_control{
    int8_t num;
    int8_t type;
    int16_t motor;
}motor_control_t;
#define LNG_MOTOR_CONTROL sizeof(motor_control_t)
```

When I solve https://github.com/officinerobotiche/uNAV.X/issues/34 I will update this message

**Comment by rbonghi** [comment]
Solve 6311e46541c6525591e75813f7f590a6909ed7f1
